title: 'TL'
description: "TL's Personal Website"
baseurl: ""
url: ""

header_pages:
  - index.md
  # - research.md
  - misc.md
  # - about.md
  # - contact.md

style: dark

footer: 'Â© 2025 Tianhao Li. All rights reserved.'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from